name: ${project.artifactId}
main: net.whg.minigames.MinigamesPlugin
version: ${project.version}
api-version: 1.17
depend: [WraithLib, WraithavenSculpt]
commands:
  mg:
    description: Minigame management commands.
    usage: /mg
