name: HavensGames-Minigames
main: net.whg.minigames.MinigamesPlugin
version: 0.1.0
api-version: 1.17
depend: [HavensGames-Utils, WraithavenSculpt]
commands:
  mg:
    description: Minigame management commands.
    usage: /mg
